apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      imagePullSecrets:
       - name: gcr
      containers:
      - name: nodeapp
        image: australia-southeast2-docker.pkg.dev/sit737-25t1-vartak-29a614e/sumedh-sit737-task5hd/nodeapp-week5:latest
        ports:
        - containerPort: 3040

