version: '3.8'

services:
  web:
    image: sumedh004/nodeapp-week5
    ports:
      - "3040:3040"
    healthcheck:
      test: ["CMD", "curl", "-i", "http://localhost:3040/ || exit 1"] 
      interval: 30s
      timeout: 10s
      retries: 10
    restart: unless-stopped
